name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Cài dependencies + chạy kiểm tra cơ bản
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test

      # CÀI RUNNER & BROWSERS CHUẨN VERSION (pin Playwright @1.56.1)
      - run: pnpm dlx @playwright/test@1.56.1 install --with-deps

      # CHẠY E2E BẰNG RUNNER ĐÃ PIN
      - run: pnpm e2e

      # Build cuối cùng
      - run: pnpm build
